name: example-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - ca-certificates
  - certifi
  - cycler
  - freetype
  - jbig
  - jpeg
  - kiwisolver
  - lcms2
  - lerc
  - libblas
  - libcblas
  - libcxx
  - libdeflate
  - libffi
  - libgfortran
  - libgfortran5
  - liblapack
  - libopenblas
  - libpng
  - libtiff
  - libwebp-base
  - llvm-openmp
  - lz4-c
  - matplotlib-base
  - ncurses
  - numpy
  - olefile
  - openjpeg
  - openssl
  - pandas
  - patsy
  - pillow
  - pip
  - pyparsing
  - python
  - python-dateutil
  - python_abi
  - pytz
  - readline
  - scipy
  - seaborn
  - seaborn-base
  - setuptools
  - six
  - sqlite
  - statsmodels
  - tk
  - tornado
  - tzdata
  - wheel
  - xz
  - zlib
  - zstd
